// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/inventory/inventory.proto

package inventory

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReserveStockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkuId    string `protobuf:"bytes,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	Quantity int32  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	OrderId  string `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
}

func (x *ReserveStockRequest) Reset() {
	*x = ReserveStockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_inventory_inventory_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReserveStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveStockRequest) ProtoMessage() {}

func (x *ReserveStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*ReserveStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *ReserveStockRequest) GetSkuId() string {
	if x != nil {
		return x.SkuId
	}
	return ""
}

func (x *ReserveStockRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ReserveStockRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type ReserveStockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success       bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ReservationId string `protobuf:"bytes,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	ErrorMessage  string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *ReserveStockResponse) Reset() {
	*x = ReserveStockResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_inventory_inventory_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReserveStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveStockResponse) ProtoMessage() {}

func (x *ReserveStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*ReserveStockResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *ReserveStockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReserveStockResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReserveStockResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ReleaseStockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReservationId string `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
}

func (x *ReleaseStockRequest) Reset() {
	*x = ReleaseStockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_inventory_inventory_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReleaseStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseStockRequest) ProtoMessage() {}

func (x *ReleaseStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*ReleaseStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *ReleaseStockRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

type ReleaseStockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success      bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *ReleaseStockResponse) Reset() {
	*x = ReleaseStockResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_inventory_inventory_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReleaseStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseStockResponse) ProtoMessage() {}

func (x *ReleaseStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*ReleaseStockResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *ReleaseStockResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReleaseStockResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type CheckStockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkuId string `protobuf:"bytes,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
}

func (x *CheckStockRequest) Reset() {
	*x = CheckStockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_inventory_inventory_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStockRequest) ProtoMessage() {}

func (x *CheckStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*CheckStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *CheckStockRequest) GetSkuId() string {
	if x != nil {
		return x.SkuId
	}
	return ""
}

type CheckStockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Available bool  `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Quantity  int32 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *CheckStockResponse) Reset() {
	*x = CheckStockResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_inventory_inventory_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStockResponse) ProtoMessage() {}

func (x *CheckStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_inventory_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*CheckStockResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *CheckStockResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *CheckStockResponse) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

var File_proto_inventory_inventory_proto protoreflect.FileDescriptor

var file_proto_inventory_inventory_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72,
	0x79, 0x2f, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79,
}

var file_proto_inventory_inventory_proto_rawDescOnce sync.Once

var file_proto_inventory_inventory_proto_rawDescData = file_proto_inventory_inventory_proto_rawDesc

func file_proto_inventory_inventory_proto_rawDescGZIP() []byte {
	file_proto_inventory_inventory_proto_rawDescOnce.Do(func() {
		file_proto_inventory_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_inventory_inventory_proto_rawDescData)
	})
	return file_proto_inventory_inventory_proto_rawDescData
}

var file_proto_inventory_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_inventory_inventory_proto_goTypes = []interface{}{
	(*ReserveStockRequest)(nil),  // 0
	(*ReserveStockResponse)(nil), // 1
	(*ReleaseStockRequest)(nil),  // 2
	(*ReleaseStockResponse)(nil), // 3
	(*CheckStockRequest)(nil),    // 4
	(*CheckStockResponse)(nil),   // 5
}

var file_proto_inventory_inventory_proto_depIdxs = []int32{
	0, // 0: inventory.InventoryService.ReserveStock:input_type -> inventory.ReserveStockRequest
	2, // 1: inventory.InventoryService.ReleaseStock:input_type -> inventory.ReleaseStockRequest
	4, // 2: inventory.InventoryService.CheckStock:input_type -> inventory.CheckStockRequest
	1, // 3: inventory.InventoryService.ReserveStock:output_type -> inventory.ReserveStockResponse
	3, // 4: inventory.InventoryService.ReleaseStock:output_type -> inventory.ReleaseStockResponse
	5, // 5: inventory.InventoryService.CheckStock:output_type -> inventory.CheckStockResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_inventory_inventory_proto_init() }

func file_proto_inventory_inventory_proto_init() {
	if File_proto_inventory_inventory_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_inventory_inventory_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReserveStockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_inventory_inventory_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReserveStockResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_inventory_inventory_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReleaseStockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_inventory_inventory_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReleaseStockResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_inventory_inventory_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckStockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_inventory_inventory_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckStockResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_inventory_inventory_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inventory_inventory_proto_goTypes,
		DependencyIndexes: file_proto_inventory_inventory_proto_depIdxs,
		MessageInfos:      file_proto_inventory_inventory_proto_msgTypes,
	}.Build()
	File_proto_inventory_inventory_proto = out.File
	file_proto_inventory_inventory_proto_rawDescGZIP()
	file_proto_inventory_inventory_proto_goTypes = nil
	file_proto_inventory_inventory_proto_depIdxs = nil
}
