// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: api/proto/v1/campaign.proto

package campaignv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CampaignService_GetCampaign_FullMethodName         = "/campaign.v1.CampaignService/GetCampaign"
	CampaignService_ListActiveCampaigns_FullMethodName = "/campaign.v1.CampaignService/ListActiveCampaigns"
	CampaignService_GetVoucherByCode_FullMethodName    = "/campaign.v1.CampaignService/GetVoucherByCode"
	CampaignService_ClaimVoucher_FullMethodName        = "/campaign.v1.CampaignService/ClaimVoucher"
	CampaignService_CalculateCart_FullMethodName       = "/campaign.v1.CampaignService/CalculateCart"
)

// CampaignServiceClient is the client API for CampaignService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CampaignServiceClient interface {
	// GetCampaign retrieves a campaign by ID
	GetCampaign(ctx context.Context, in *GetCampaignRequest, opts ...grpc.CallOption) (*GetCampaignResponse, error)
	// ListActiveCampaigns retrieves all active campaigns
	ListActiveCampaigns(ctx context.Context, in *ListActiveCampaignsRequest, opts ...grpc.CallOption) (*ListActiveCampaignsResponse, error)
	// GetVoucherByCode retrieves a voucher by code
	GetVoucherByCode(ctx context.Context, in *GetVoucherByCodeRequest, opts ...grpc.CallOption) (*GetVoucherByCodeResponse, error)
	// ClaimVoucher claims a voucher for a user
	ClaimVoucher(ctx context.Context, in *ClaimVoucherRequest, opts ...grpc.CallOption) (*ClaimVoucherResponse, error)
	// CalculateCart calculates cart discount with voucher
	CalculateCart(ctx context.Context, in *CalculateCartRequest, opts ...grpc.CallOption) (*CalculateCartResponse, error)
}

type campaignServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCampaignServiceClient(cc grpc.ClientConnInterface) CampaignServiceClient {
	return &campaignServiceClient{cc}
}

func (c *campaignServiceClient) GetCampaign(ctx context.Context, in *GetCampaignRequest, opts ...grpc.CallOption) (*GetCampaignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCampaignResponse)
	err := c.cc.Invoke(ctx, CampaignService_GetCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) ListActiveCampaigns(ctx context.Context, in *ListActiveCampaignsRequest, opts ...grpc.CallOption) (*ListActiveCampaignsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListActiveCampaignsResponse)
	err := c.cc.Invoke(ctx, CampaignService_ListActiveCampaigns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) GetVoucherByCode(ctx context.Context, in *GetVoucherByCodeRequest, opts ...grpc.CallOption) (*GetVoucherByCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVoucherByCodeResponse)
	err := c.cc.Invoke(ctx, CampaignService_GetVoucherByCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) ClaimVoucher(ctx context.Context, in *ClaimVoucherRequest, opts ...grpc.CallOption) (*ClaimVoucherResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimVoucherResponse)
	err := c.cc.Invoke(ctx, CampaignService_ClaimVoucher_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) CalculateCart(ctx context.Context, in *CalculateCartRequest, opts ...grpc.CallOption) (*CalculateCartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateCartResponse)
	err := c.cc.Invoke(ctx, CampaignService_CalculateCart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CampaignServiceServer is the server API for CampaignService service.
// All implementations must embed UnimplementedCampaignServiceServer
// for forward compatibility.
type CampaignServiceServer interface {
	// GetCampaign retrieves a campaign by ID
	GetCampaign(context.Context, *GetCampaignRequest) (*GetCampaignResponse, error)
	// ListActiveCampaigns retrieves all active campaigns
	ListActiveCampaigns(context.Context, *ListActiveCampaignsRequest) (*ListActiveCampaignsResponse, error)
	// GetVoucherByCode retrieves a voucher by code
	GetVoucherByCode(context.Context, *GetVoucherByCodeRequest) (*GetVoucherByCodeResponse, error)
	// ClaimVoucher claims a voucher for a user
	ClaimVoucher(context.Context, *ClaimVoucherRequest) (*ClaimVoucherResponse, error)
	// CalculateCart calculates cart discount with voucher
	CalculateCart(context.Context, *CalculateCartRequest) (*CalculateCartResponse, error)
	mustEmbedUnimplementedCampaignServiceServer()
}

// UnimplementedCampaignServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCampaignServiceServer struct{}

func (UnimplementedCampaignServiceServer) GetCampaign(context.Context, *GetCampaignRequest) (*GetCampaignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCampaign not implemented")
}
func (UnimplementedCampaignServiceServer) ListActiveCampaigns(context.Context, *ListActiveCampaignsRequest) (*ListActiveCampaignsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListActiveCampaigns not implemented")
}
func (UnimplementedCampaignServiceServer) GetVoucherByCode(context.Context, *GetVoucherByCodeRequest) (*GetVoucherByCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVoucherByCode not implemented")
}
func (UnimplementedCampaignServiceServer) ClaimVoucher(context.Context, *ClaimVoucherRequest) (*ClaimVoucherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimVoucher not implemented")
}
func (UnimplementedCampaignServiceServer) CalculateCart(context.Context, *CalculateCartRequest) (*CalculateCartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateCart not implemented")
}
func (UnimplementedCampaignServiceServer) mustEmbedUnimplementedCampaignServiceServer() {}
func (UnimplementedCampaignServiceServer) testEmbeddedByValue()                         {}

// UnsafeCampaignServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CampaignServiceServer will
// result in compilation errors.
type UnsafeCampaignServiceServer interface {
	mustEmbedUnimplementedCampaignServiceServer()
}

func RegisterCampaignServiceServer(s grpc.ServiceRegistrar, srv CampaignServiceServer) {
	// If the following call pancis, it indicates UnimplementedCampaignServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CampaignService_ServiceDesc, srv)
}

func _CampaignService_GetCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).GetCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignService_GetCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).GetCampaign(ctx, req.(*GetCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_ListActiveCampaigns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActiveCampaignsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).ListActiveCampaigns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignService_ListActiveCampaigns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).ListActiveCampaigns(ctx, req.(*ListActiveCampaignsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_GetVoucherByCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVoucherByCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).GetVoucherByCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignService_GetVoucherByCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).GetVoucherByCode(ctx, req.(*GetVoucherByCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_ClaimVoucher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimVoucherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).ClaimVoucher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignService_ClaimVoucher_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).ClaimVoucher(ctx, req.(*ClaimVoucherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_CalculateCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).CalculateCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignService_CalculateCart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).CalculateCart(ctx, req.(*CalculateCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CampaignService_ServiceDesc is the grpc.ServiceDesc for CampaignService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CampaignService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "campaign.v1.CampaignService",
	HandlerType: (*CampaignServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCampaign",
			Handler:    _CampaignService_GetCampaign_Handler,
		},
		{
			MethodName: "ListActiveCampaigns",
			Handler:    _CampaignService_ListActiveCampaigns_Handler,
		},
		{
			MethodName: "GetVoucherByCode",
			Handler:    _CampaignService_GetVoucherByCode_Handler,
		},
		{
			MethodName: "ClaimVoucher",
			Handler:    _CampaignService_ClaimVoucher_Handler,
		},
		{
			MethodName: "CalculateCart",
			Handler:    _CampaignService_CalculateCart_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/v1/campaign.proto",
}
