apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexuscommerce-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/TanFuc/FDemo-microservices.git
    targetRevision: develop
    path: deploy/helm/nexus-service
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: nexus-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
