// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt   string `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt   string `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Item) Reset()         { *x = Item{} }
func (x *Item) String() string { return protoimpl.X.MessageStringOf(x) }
func (*Item) ProtoMessage()    {}
func (x *Item) ProtoReflect() protoreflect.Message { return nil }
func (*Item) Descriptor() ([]byte, []int) { return nil, nil }

func (x *Item) GetId() string          { if x != nil { return x.Id }; return "" }
func (x *Item) GetName() string        { if x != nil { return x.Name }; return "" }
func (x *Item) GetDescription() string { if x != nil { return x.Description }; return "" }
func (x *Item) GetCreatedAt() string   { if x != nil { return x.CreatedAt }; return "" }
func (x *Item) GetUpdatedAt() string   { if x != nil { return x.UpdatedAt }; return "" }

type GetItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetItemRequest) Reset()         { *x = GetItemRequest{} }
func (x *GetItemRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*GetItemRequest) ProtoMessage()    {}
func (x *GetItemRequest) ProtoReflect() protoreflect.Message { return nil }
func (*GetItemRequest) Descriptor() ([]byte, []int) { return nil, nil }
func (x *GetItemRequest) GetId() string { if x != nil { return x.Id }; return "" }

type GetItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *Item `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *GetItemResponse) Reset()         { *x = GetItemResponse{} }
func (x *GetItemResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*GetItemResponse) ProtoMessage()    {}
func (x *GetItemResponse) ProtoReflect() protoreflect.Message { return nil }
func (*GetItemResponse) Descriptor() ([]byte, []int) { return nil, nil }
func (x *GetItemResponse) GetItem() *Item { if x != nil { return x.Item }; return nil }

type CreateItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *CreateItemRequest) Reset()         { *x = CreateItemRequest{} }
func (x *CreateItemRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*CreateItemRequest) ProtoMessage()    {}
func (x *CreateItemRequest) ProtoReflect() protoreflect.Message { return nil }
func (*CreateItemRequest) Descriptor() ([]byte, []int) { return nil, nil }
func (x *CreateItemRequest) GetName() string        { if x != nil { return x.Name }; return "" }
func (x *CreateItemRequest) GetDescription() string { if x != nil { return x.Description }; return "" }

type CreateItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *Item `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *CreateItemResponse) Reset()         { *x = CreateItemResponse{} }
func (x *CreateItemResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*CreateItemResponse) ProtoMessage()    {}
func (x *CreateItemResponse) ProtoReflect() protoreflect.Message { return nil }
func (*CreateItemResponse) Descriptor() ([]byte, []int) { return nil, nil }
func (x *CreateItemResponse) GetItem() *Item { if x != nil { return x.Item }; return nil }

type ListItemsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page  int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ListItemsRequest) Reset()         { *x = ListItemsRequest{} }
func (x *ListItemsRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ListItemsRequest) ProtoMessage()    {}
func (x *ListItemsRequest) ProtoReflect() protoreflect.Message { return nil }
func (*ListItemsRequest) Descriptor() ([]byte, []int) { return nil, nil }
func (x *ListItemsRequest) GetPage() int32  { if x != nil { return x.Page }; return 0 }
func (x *ListItemsRequest) GetLimit() int32 { if x != nil { return x.Limit }; return 0 }

type ListItemsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total int32   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *ListItemsResponse) Reset()         { *x = ListItemsResponse{} }
func (x *ListItemsResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*ListItemsResponse) ProtoMessage()    {}
func (x *ListItemsResponse) ProtoReflect() protoreflect.Message { return nil }
func (*ListItemsResponse) Descriptor() ([]byte, []int) { return nil, nil }
func (x *ListItemsResponse) GetItems() []*Item { if x != nil { return x.Items }; return nil }
func (x *ListItemsResponse) GetTotal() int32   { if x != nil { return x.Total }; return 0 }

type DeleteItemRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteItemRequest) Reset()         { *x = DeleteItemRequest{} }
func (x *DeleteItemRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*DeleteItemRequest) ProtoMessage()    {}
func (x *DeleteItemRequest) ProtoReflect() protoreflect.Message { return nil }
func (*DeleteItemRequest) Descriptor() ([]byte, []int) { return nil, nil }
func (x *DeleteItemRequest) GetId() string { if x != nil { return x.Id }; return "" }

type DeleteItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteItemResponse) Reset()         { *x = DeleteItemResponse{} }
func (x *DeleteItemResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*DeleteItemResponse) ProtoMessage()    {}
func (x *DeleteItemResponse) ProtoReflect() protoreflect.Message { return nil }
func (*DeleteItemResponse) Descriptor() ([]byte, []int) { return nil, nil }
func (x *DeleteItemResponse) GetSuccess() bool { if x != nil { return x.Success }; return false }

var File_api_proto_service_proto protoreflect.FileDescriptor

var _ sync.Once
var _ reflect.Type
