app:
  name: notification-service
  env: development
  port: "8083"
  grpc_port: "50053"
  auth_grpc_addr: localhost:50051
  debug: true

nats:
  url: nats://localhost:4222
  stream_name: NOTIFICATIONS
  subject: notification.>

rabbitmq:
  url: amqp://guest:guest@localhost:5672/

mongodb:
  uri: mongodb://localhost:27017
  database: notification_service

smtp:
  host: smtp.gmail.com
  port: 587
  user: ""
  pass: ""
  from: ""

websocket:
  enabled: true
  max_connections: 10000
  ping_interval: 30s
  pong_wait: 60s
  write_wait: 10s
  max_message_size: 524288
  read_buffer_size: 1024
  write_buffer_size: 1024
