app:
  name: template-service
  env: development
  port: "8080"
  grpc_port: "50051"
  debug: true

database:
  host: localhost
  port: "5432"
  user: postgres
  password: postgres
  name: template_service
  ssl_mode: disable
  max_idle_conns: 10
  max_open_conns: 100
