[request_definition]
r = sub, obj, act, dom, attrs

[policy_definition]
p = sub, obj, act, eft, dom, condition

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = (g(r.sub, p.sub, r.dom) || r.sub == p.sub) && (r.obj == p.obj || p.obj == "*") && (r.act == p.act || p.act == "*") && (r.dom == p.dom || p.dom == "*") && (p.condition == "" || eval(p.condition))
